# 构建阶段
FROM python:3.11.14-trixie as builder

# 安装构建依赖
RUN apt update && apt install -y --no-install-recommends tzdata git gcc build-essential libc-dev libjpeg-dev libffi-dev libxml2-dev libxslt-dev zlib1g-dev libyaml-dev && \
    apt install -y linux-headers-generic || apt install -y linux-headers-amd64 || apt install -y linux-headers-arm64 || apt install -y linux-headers-armhf \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone && \
    git clone --depth=1 https://github.com/txperl/PixivBiu.git && \
    cd /PixivBiu && \
    mkdir ./.pkg/code && \
    mkdir ./.pkg/public && \
    cp -r ./altfe/ ./.pkg/code/altfe/ && \
    cp -r ./app/ ./.pkg/code/app/ && \
    cp ./main.py ./.pkg/code/ && \
    cp -r ./usr/ ./.pkg/public/usr/ && \
    cp ./app/config/biu_default.yml ./.pkg/public/config.yml && \
    cp ./LICENSE ./.pkg/public/ && \
    cp ./README.md ./.pkg/public/ && \      
    pip install -r requirements.txt --no-cache-dir && \
    pip install pyinstaller --no-cache-dir && \
    python3 /PixivBiu/.pkg/py-pkger.py auto

# 运行阶段
FROM debian:stable-slim as main

# 设置时区
ENV TZ=Asia/Shanghai

RUN apt update && apt install -y --no-install-recommends ca-certificates libjpeg62-turbo libffi8 libxml2 libxslt1.1 zlib1g libyaml-0-2 && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
    groupadd -r -g 1000 appuser && \
    useradd -r -u 1000 -g appuser appuser && \
    mkdir -p /Pixiv/downlaods && chown -R appuser:appuser /Pixiv/downlaods

# 从构建阶段复制可执行文件
COPY --from=builder --chown=appuser:appuser /PixivBiu/.pkg/dist/ /Pixiv/

# 从GitHub仓库复制entrypoint.sh
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 设置环境变量
ENV sys.host="0.0.0.0:4001"
ENV sys.autoOpen=false
ENV sys.ignoreOutdated=true

# 暴露端口
EXPOSE 4001

# 设置工作目录
WORKDIR /Pixiv

# 使用entrypoint脚本
ENTRYPOINT ["/entrypoint.sh"]