FROM alpine:latest
RUN apk add -U --no-cache python3 python3-dev py3-pip tzdata git gcc libc-dev musl-dev linux-headers jpeg-dev zlib-dev && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    git clone --depth=1 https://github.com/zzcabc/PixivBiu.git && \
    mkdir Pixiv && \
    mkdir /PixivBiu/.pkg/code && \
    mkdir /PixivBiu/.pkg/public && \
    cp -r /PixivBiu/altfe/                        /PixivBiu/.pkg/code/altfe/ && \
    cp -r /PixivBiu/app/                          /PixivBiu/.pkg/code/app/ && \
    cp /PixivBiu/main.py                          /PixivBiu/.pkg/code/ && \
    cp -r /PixivBiu/usr/                          /PixivBiu/.pkg/public/usr/ && \
    cp /PixivBiu/app/config/biu_default.yml       /PixivBiu/.pkg/public/config.yml && \
    cp /PixivBiu/LICENSE                          /PixivBiu/.pkg/public/ && \
    cp /PixivBiu/README.md                        /PixivBiu/.pkg/public/ && \
    pip install -r /PixivBiu/requirements.txt --no-cache-dir && \
    pip install pyinstaller --no-cache-dir && \
    python3 /PixivBiu/.pkg/py-pkger.py auto && \
    mv /PixivBiu/.pkg/dist/* /Pixiv  && \
    rm -rf PixivBiu/ /Pixiv/config.yml /Pixiv/LICENSE /Pixiv/README.md && \
    apk del python3 python3-dev py3-pip tzdata git gcc libc-dev musl-dev linux-headers jpeg-dev zlib-dev && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*
EXPOSE 4001
ENV sys.host="0.0.0.0:4001"
ENV sys.autoOpen=false
ENV sys.ignoreOutdated=true
ENTRYPOINT ["/Pixiv/main"]