#!/bin/sh
set -e

# 环境变量默认值
USER_PATH="/Pixiv/usr"
CONFIG_FILE="/Pixiv/config.yml"


PIXIVBIU_SERVER_HOST="${PIXIVBIU_SERVER_HOST:-0.0.0.0}"
PIXIVBIU_SERVER_PORT="${PIXIVBIU_SERVER_PORT:-4001}"
PIXIVBIU_SERVER_PORT_FALLBACK="${PIXIVBIU_SERVER_PORT_FALLBACK:-false}"
PIXIVBIU_SERVER_TIMEOUTS_READ="${PIXIVBIU_SERVER_TIMEOUTS_READ:-15s}"
PIXIVBIU_SERVER_TIMEOUTS_WRITE="${PIXIVBIU_SERVER_TIMEOUTS_WRITE:-15s}"
PIXIVBIU_SERVER_TIMEOUTS_SHUTDOWN="${PIXIVBIU_SERVER_TIMEOUTS_SHUTDOWN:-15s}"

PIXIVBIU_LOG_LEVEL="${PIXIVBIU_LOG_LEVEL:-info}"
PIXIVBIU_LOG_FORMAT="${PIXIVBIU_LOG_FORMAT:-text}"


PIXIVBIU_PIXIV_PROXY="${PIXIVBIU_PIXIV_PROXY}"
PIXIVBIU_PIXIV_BYPASS_SNI="${PIXIVBIU_PIXIV_BYPASS_SNI:-false}"
PIXIVBIU_PIXIV_STATE_FILE="${PIXIVBIU_PIXIV_STATE_FILE:-/Pixiv/usr/state.json}"


PIXIVBIU_DOWNLOAD_OUTPUT_DIR="${PIXIVBIU_DOWNLOAD_OUTPUT_DIR:-/Pixiv/downloads}"
PIXIVBIU_DOWNLOAD_MAX_CONCURRENT="${PIXIVBIU_DOWNLOAD_MAX_CONCURRENT:-4}"
PIXIVBIU_DOWNLOAD_HTTP_TIMEOUT="${PIXIVBIU_DOWNLOAD_HTTP_TIMEOUT:-60}"
PIXIVBIU_DOWNLOAD_RETRY_MAX="${PIXIVBIU_DOWNLOAD_RETRY_MAX:-3}"
PIXIVBIU_DOWNLOAD_RETRY_INITIAL_BACKOFF="${PIXIVBIU_DOWNLOAD_RETRY_INITIAL_BACKOFF:-1s}"
PIXIVBIU_DOWNLOAD_UGOIRA_FORMAT="${PIXIVBIU_DOWNLOAD_UGOIRA_FORMAT}"
PIXIVBIU_DOWNLOAD_STORE_FILES="${PIXIVBIU_DOWNLOAD_STORE_FILES:-false}"
PIXIVBIU_DOWNLOAD_STORE_FILE="${PIXIVBIU_DOWNLOAD_STORE_FILE:-/Pixiv/usr/downloads.json}"

PIXIVBIU_IMAGE_CACHE_MAX_SIZE_MB="${PIXIVBIU_IMAGE_CACHE_MAX_SIZE_MB:-1024}"

PIXIVBIU_SEARCH_SAMPLE_PAGES="${PIXIVBIU_SEARCH_SAMPLE_PAGES:-5}"
PIXIVBIU_SEARCH_SAMPLE_CONCURRENCY="${PIXIVBIU_SEARCH_SAMPLE_CONCURRENCY:-3}"


PIXIVBIU_APP_UPDATE_ENABLED=false


UMASK="${UMASK:-022}"
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"

# 设置 umask
umask "${UMASK}"

echo "Starting PixivBiu with PUID:PGID = ${PUID}:${PGID}, UMASK = ${UMASK}"

# 创建用户和组（仅当 PUID 或 PGID 非 0 时）
if [ "${PUID}" -ne 0 ] || [ "${PGID}" -ne 0 ]; then
    # 检查组是否存在，若不存在则创建
    if ! getent group "${PGID}" >/dev/null 2>&1; then
        addgroup -g "${PGID}" -S appgroup
    fi
    # 检查用户是否存在，若不存在则创建
    if ! getent passwd "${PUID}" >/dev/null 2>&1; then
        adduser -u "${PUID}" -G appgroup -S -D -h /Pixiv appuser
    fi
fi

# 确保目录存在
mkdir -p "${PIXIVBIU_DOWNLOAD_OUTPUT_DIR}" "${USER_PATH}"
echo "Ensured directories: ${PIXIVBIU_DOWNLOAD_OUTPUT_DIR}, ${USER_PATH}"

# 设置目录所有权（如果需要）
if [ "${PUID}" -ne 0 ] || [ "${PGID}" -ne 0 ]; then
    chown -R "${PUID}:${PGID}" "${PIXIVBIU_DOWNLOAD_OUTPUT_DIR}" "${USER_PATH}"
    echo "Set ownership to ${PUID}:${PGID} for data directories"
fi

# 如果存在配置文件，也一并修改权限（可选）
[ -f "${CONFIG_FILE}" ] && chown "${PUID}:${PGID}" "${CONFIG_FILE}"

# 切换用户并执行程序
if [ "${PUID}" -eq 0 ] && [ "${PGID}" -eq 0 ]; then
    # 以 root 直接运行
    exec /Pixiv/pixivbiu
else
    # 使用 su-exec 切换用户执行
    exec su-exec "${PUID}:${PGID}" /Pixiv/pixivbiu
fi