name: Update_Docker_Readme
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/Update_Docker_Readme.yaml

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pixivbiu
    steps:
      - 
        name: Checkout
        uses: actions/checkout@main

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Update DockerHub Description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          provider: dockerhub
          readme_file: ./README.md